docker run --rm --name workbench -d \
    -v /tmp:/HostData \
    -p 8787:8787 \
    -p 2200:22 \
    -p 1433:1433 \
    -e CONTAINER_USER_USERNAME=user \
    -e CONTAINER_USER_PASSWORD=password \
    -e 'ACCEPT_EULA=Y' \
    -e 'SA_PASSWORD=yourStrong(!)Password' \
    --privileged \
    -d sqlserverworkbench